function AdminCaseNew({ onToast }) {
  const [, navigate] = useLocation();
  const editId = new URLSearchParams(window.location.search).get('edit');
  const existing = readStore('negotiator-admin-cases', []).find(item => item.id === editId);
  const [step, setStep] = useState(1);
  const [title, setTitle] = useState(existing?.title || '');
  const [category, setCategory] = useState(existing?.category || categories[0].name);
  const [description, setDescription] = useState(existing?.description || '');
  const [goal, setGoal] = useState(existing?.goal || '');
  const [difficulty, setDifficulty] = useState(existing?.difficulty || 'Средний');
  const save = () => { const items = readStore('negotiator-admin-cases', []); const newCase = { id: existing?.id || `custom-${Date.now()}`, title: title || 'Новый переговорный сценарий', category, description: description || 'Сценарий для практики делового разговора.', goal: goal || 'Договориться о следующем шаге.', difficulty, custom: true, status: 'Готов к приглашению' }; const next = existing ? items.map(item => item.id === existing.id ? newCase : item) : [...items, newCase]; saveStore('negotiator-admin-cases', next); onToast(existing ? 'Кейс обновлён' : 'Кейс готов к приглашению'); navigate('/admin/cases'); };
  return <><div className="page-header"><div><span className="eyebrow">Новый кейс · шаг {step} из 2</span><h1 className="display">Соберите ситуацию для команды.</h1></div><button className="btn btn-quiet" onClick={() => navigate('/admin/cases')}><ArrowLeft size={15} /> Отмена</button></div><div className="stepper"><span className="active" /><span className={step === 2 ? 'active' : ''} /></div><div className="card form-card" style={{ maxWidth: 760 }}>{step === 1 ? <><div className="field"><label htmlFor="admin-title">Название кейса</label><input id="admin-title" value={title} onChange={e => setTitle(e.target.value)} placeholder="Например: Обсуждение бюджета проекта" data-testid="input-admin-title" /></div><div className="field" style={{ marginTop: 18 }}><label htmlFor="admin-category">Категория</label><select id="admin-category" value={category} onChange={e => setCategory(e.target.value)}>{categories.map(item => <option key={item.name}>{item.name}</option>)}</select></div><div className="field" style={{ marginTop: 18 }}><label htmlFor="admin-description">Ситуация</label><textarea id="admin-description" value={description} onChange={e => setDescription(e.target.value)} placeholder="Что произошло до начала разговора?" /></div><button className="btn btn-primary" style={{ marginTop: 23 }} onClick={() => setStep(2)} data-testid="button-admin-next">Дальше <ArrowRight size={16} /></button></> : <><div className="field"><label htmlFor="admin-goal">Цель участника</label><textarea id="admin-goal" value={goal} onChange={e => setGoal(e.target.value)} placeholder="Какой результат должен получить участник?" /></div><div className="field" style={{ marginTop: 18 }}><label>Сложность</label><div className="option-grid">{(['Лёгкий', 'Средний', 'Сложный']).map(item => <button className={`option ${difficulty === item ? 'selected' : ''}`} key={item} onClick={() => setDifficulty(item)}>{item}</button>)}</div></div><div className="card" style={{ marginTop: 22, padding: 17, background: 'rgba(157,227,229,.08)', borderColor: 'rgba(157,227,229,.2)' }}><div style={{ display: 'flex', gap: 10 }}><Info size={17} color="#9de3e5" /><span className="soft" style={{ fontSize: 12, lineHeight: 1.5 }}>После сохранения кейс получит статус «Готов к приглашению». Вы сможете скопировать ссылку из списка.</span></div></div><div style={{ display: 'flex', gap: 10, marginTop: 23 }}><button className="btn btn-quiet" onClick={() => setStep(1)}><ArrowLeft size={15} /> Назад</button><button className="btn btn-primary" onClick={save} style={{ flex: 1 }} data-testid="button-save-admin-case"><Check size={15} /> Сохранить и подготовить</button></div></>}</div></>;
}
