"""add category to scenarios

Revision ID: 47024aff1d2c
Revises: 8317902b5f17
Create Date: 2026-09-14 01:10:42.607245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47024aff1d2c'
down_revision: Union[str, Sequence[str], None] = '8317902b5f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_scenarios_category'), 'scenarios', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_category'), table_name='scenarios')
    op.drop_column('scenarios', 'category')
    # ### end Alembic commands ###
