function AuthPage({ mode, admin, onAuth }) {
  const [, navigate] = useLocation();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const submit = (event) => { event.preventDefault(); if (!email || !password || (mode === 'register' && !name)) { setError('Заполните все обязательные поля'); return; } const user = { name: name || (admin ? 'Редактор кейсов' : 'Алексей'), email, role: admin ? 'admin' : 'user', status: admin ? 'active' : mode === 'register' ? 'pending_onboarding' : 'active', xp: 280, difficulty: 'Средний', categories: ['Управление командой'] }; onAuth(user); navigate(admin ? '/admin/cases' : mode === 'register' ? '/onboarding' : '/profile'); };
  return <div className="auth-wrap"><div className="card auth-card"><span className="eyebrow">{admin ? 'Рабочее пространство автора' : 'Личная арена'}</span><h1 className="display">{mode === 'login' ? 'С возвращением.' : 'Начнём с вашего голоса.'}</h1><p className="muted">{admin ? 'Создавайте кейсы для приглашённых команд.' : 'Регистрация нужна только, чтобы сохранить ваш прогресс на этом устройстве.'}</p><form onSubmit={submit}>{mode === 'register' && <div className="field"><label htmlFor="name">Как вас зовут</label><input id="name" value={name} onChange={e => setName(e.target.value)} placeholder="Имя и фамилия" autoComplete="name" data-testid="input-name" /></div>}<div className="field"><label htmlFor="email">Почта</label><input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.ru" autoComplete="email" data-testid="input-email" /></div><div className="field"><label htmlFor="password">Пароль</label><input id="password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Не менее 8 символов" minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} data-testid="input-password" /></div>{error && <span className="form-error">{error}</span>}<button className="btn btn-primary" type="submit" data-testid="button-submit-auth">{mode === 'login' ? 'Войти в арену' : 'Создать профиль'} <ArrowRight size={16} /></button></form><div className="form-footer">{admin ? <>Не администратор? <Link href={mode === 'login' ? '/login' : '/register'}>{mode === 'login' ? 'Войти как пользователь' : 'Зарегистрироваться как пользователь'}</Link></> : <>{mode === 'login' ? 'Нет профиля? ' : 'Уже были здесь? '}<Link href={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Создать его' : 'Войти'}</Link></>}</div><div style={{ textAlign: 'center', marginTop: 17 }}><Link href={admin ? (mode === 'login' ? '/register/admin' : '/login/admin') : (mode === 'login' ? '/register/admin' : '/login/admin')} className="muted" style={{ fontSize: 11 }}>{admin ? 'Перейти к пользовательскому входу' : 'Вход для администратора'}</Link></div></div></div>;
}
