"""add difficulty to sessions

Revision ID: 05ae2417f477
Revises: 47024aff1d2c
Create Date: 2026-09-14 01:18:48.418378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ae2417f477'
down_revision: Union[str, Sequence[str], None] = '47024aff1d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiation_sessions', sa.Column('difficulty', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negotiation_sessions', 'difficulty')
    # ### end Alembic commands ###
