"""add relationship and power balance

Revision ID: 232407e7fb93
Revises: f5916f575cf7
Create Date: 2026-09-14 02:17:57.916237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232407e7fb93'
down_revision: Union[str, Sequence[str], None] = 'f5916f575cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiation_sessions', sa.Column('relationship', sa.String(length=30), nullable=True))
    op.add_column('negotiation_sessions', sa.Column('power_balance', sa.String(length=30), nullable=True))
    op.add_column('scenarios', sa.Column('default_relationship', sa.String(length=30), nullable=True))
    op.add_column('scenarios', sa.Column('default_power_balance', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'default_power_balance')
    op.drop_column('scenarios', 'default_relationship')
    op.drop_column('negotiation_sessions', 'power_balance')
    op.drop_column('negotiation_sessions', 'relationship')
    # ### end Alembic commands ###
