"""add skill_progress table

Revision ID: 4f77ec0c404e
Revises: daf2664f5f09
Create Date: 2026-09-22 19:57:41.783902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f77ec0c404e'
down_revision: Union[str, Sequence[str], None] = 'daf2664f5f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric', name='uq_user_metric')
    )
    op.create_index(op.f('ix_skill_progress_metric'), 'skill_progress', ['metric'], unique=False)
    op.create_index(op.f('ix_skill_progress_user_id'), 'skill_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_progress_user_id'), table_name='skill_progress')
    op.drop_index(op.f('ix_skill_progress_metric'), table_name='skill_progress')
    op.drop_table('skill_progress')
    # ### end Alembic commands ###
