"""add spin batna emotion metrics

Revision ID: f5916f575cf7
Revises: 05ae2417f477
Create Date: 2026-09-14 01:38:39.442403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5916f575cf7'
down_revision: Union[str, Sequence[str], None] = '05ae2417f477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('spin_score', sa.Integer(), nullable=True))
    op.add_column('analysis_reports', sa.Column('batna_score', sa.Integer(), nullable=True))
    op.add_column('analysis_reports', sa.Column('emotion_control_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'emotion_control_score')
    op.drop_column('analysis_reports', 'batna_score')
    op.drop_column('analysis_reports', 'spin_score')
    # ### end Alembic commands ###
