// Брифинг: описание цели и проверка микрофона
function Briefing() {
  const [, navigate] = useLocation();
  const params = new URLSearchParams(window.location.search);
  const item = cases.find(entry => entry.id === params.get('case')) || cases[0];
  const difficulty = params.get('difficulty') || item.difficulty;
  const [mic, setMic] = useState('idle');
  const checkMic = () => { setMic('checking'); window.setTimeout(() => setMic('ready'), 900); };
  return <div className="briefing-card card"><span className="eyebrow">Брифинг · 2 минуты</span><h1 className="display" style={{ fontSize: 'clamp(34px,5vw,58px)', margin: '18px 0 14px' }}>Войдите в разговор с ясной целью.</h1><p className="muted" style={{ maxWidth: 650, lineHeight: 1.65 }}>{item.description}</p><div className="briefing-meta"><div className="meta-box"><small>СЦЕНАРИЙ</small><strong>{item.title}</strong></div><div className="meta-box"><small>СЛОЖНОСТЬ</small><strong>{difficulty}</strong></div><div className="meta-box"><small>БАЗОВАЯ НАГРАДА</small><strong>{difficulty === 'Лёгкий' ? 50 : difficulty === 'Сложный' ? 200 : 100} XP</strong></div></div><div className="card" style={{ padding: 20, background: 'rgba(17,14,37,.28)' }}><span className="eyebrow">Ваша цель</span><p style={{ margin: '12px 0 0', lineHeight: 1.6 }}>{item.goal}</p></div><div className="mic-check"><div className="mic-icon">{mic === 'checking' ? <Zap size={20} /> : <Mic2 size={20} />}</div><div style={{ flex: 1 }}><strong>{mic === 'ready' ? 'Микрофон готов' : mic === 'checking' ? 'Проверяем микрофон…' : 'Проверьте микрофон'}</strong><p className="muted" style={{ fontSize: 12, margin: '5px 0 0' }}>{mic === 'ready' ? 'Голос слышен. Можно начинать.' : 'Нажмите, чтобы убедиться, что вас хорошо слышно.'}</p></div>{mic !== 'ready' && <button className="btn btn-small" onClick={checkMic} data-testid="button-check-mic">Проверить</button>}{mic === 'ready' && <Check size={19} color="#9de3e5" />}</div><button className="btn btn-primary" style={{ width: '100%' }} disabled={mic !== 'ready'} onClick={() => navigate(`/session?case=${item.id}`)} data-testid="button-start-session"><Mic size={16} /> Начать разговор</button></div>;
}
