// Конструктор: выбор кейса, сложности и условий
function ConstructorPage() {
  const [, navigate] = useLocation();
  const params = new URLSearchParams(window.location.search);
  const [category, setCategory] = useState(params.get('case') ? cases.find(item => item.id === params.get('case'))?.category || categories[0].name : categories[0].name);
  const [caseId, setCaseId] = useState(params.get('case') || cases[0].id);
  const [difficulty, setDifficulty] = useState('Средний');
  const [context, setContext] = useState('');
  const categoryCases = cases.filter(item => item.category === category);
  const selected = cases.find(item => item.id === caseId) || cases[0];
  useEffect(() => { if (categoryCases.length && !categoryCases.some(item => item.id === caseId)) setCaseId(categoryCases[0].id); }, [category]);
  return <><div className="page-header"><div><span className="eyebrow">Конструктор</span><h1 className="display">Соберите разговор под себя.</h1><p className="muted">Настройка займёт меньше минуты. После неё — брифинг и голосовая арена.</p></div><Link href="/catalog" className="btn btn-quiet"><ArrowLeft size={15} /> Каталог</Link></div><div className="constructor-grid"><div className="card form-card"><div className="field"><label htmlFor="category">Категория</label><select id="category" value={category} onChange={e => setCategory(e.target.value)} data-testid="select-category">{categories.map(item => <option key={item.name}>{item.name}</option>)}</select></div><div className="field" style={{ marginTop: 20 }}><label htmlFor="case">Кейс</label><select id="case" value={caseId} onChange={e => setCaseId(e.target.value)} data-testid="select-case">{categoryCases.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div><div className="field" style={{ marginTop: 20 }}><label>Сложность</label><div className="option-grid">{(['Лёгкий', 'Средний', 'Сложный']).map(item => <button key={item} className={`option ${difficulty === item ? 'selected' : ''}`} onClick={() => setDifficulty(item)} data-testid={`button-difficulty-${item}`}>{item}
  <span style={{ display: 'block', color: '#9de3e5', fontFamily: 'DM Mono', marginTop: 7 }}>+{item === 'Лёгкий' ? 50 : item === 'Средний' ? 100 : 200} XP</span></button>)}</div></div><div className="field" style={{ marginTop: 20 }}><label htmlFor="context">Дополнительный контекст <span className="muted">(необязательно)</span></label><textarea id="context" value={context} onChange={e => setContext(e.target.value)} placeholder="Например: разговор состоится после квартального ревью..." data-testid="textarea-context" /></div><button className="btn btn-primary" style={{ width: '100%', marginTop: 22 }} onClick={() => navigate(`/briefing?case=${selected.id}&difficulty=${difficulty}&context=${encodeURIComponent(context)}`)} data-testid="button-to-briefing">Перейти к брифингу <ArrowRight size={16} /></button></div><div className="card" style={{ padding: 28, minHeight: 400, background: 'radial-gradient(circle at 80% 10%,rgba(188,160,255,.25),transparent 42%),rgba(39,32,72,.8)' }}><span className="eyebrow">Предпросмотр</span><h2 className="display" style={{ fontSize: 36, margin: '21px 0 12px' }}>{selected.title}</h2><p className="soft" style={{ lineHeight: 1.65, fontSize: 14 }}>{selected.description}</p><div style={{ marginTop: 45, paddingTop: 19, borderTop: '1px solid rgba(255,255,255,.1)' }}><span className="eyebrow">Цель</span><p className="soft" style={{ fontSize: 14, lineHeight: 1.6 }}>{selected.goal}</p></div><div style={{ display: 'flex', gap: 8, marginTop: 25 }}><span className="tag">{category}</span><span className="tag tag-warm">{difficulty}</span></div></div></div></>;
}
