// Онбординг (выбор категорий и опыта для новичка)
function Onboarding({ onComplete }) {
  const [, navigate] = useLocation();
  const [step, setStep] = useState(1);
  const [selected, setSelected] = useState([]);
  const [experience, setExperience] = useState('');
  const toggle = (name) => setSelected(items => items.includes(name) ? items.filter(item => item !== name) : items.length < 3 ? [...items, name] : items);
  const finish = () => { if (!experience) return; const difficulty = experience === 'Новичок' ? 'Лёгкий' : experience === 'Эксперт' ? 'Сложный' : 'Средний'; const current = readStore('negotiator-user', defaultUser); const user = { ...current, status: 'active', categories: selected, experience, difficulty }; onComplete(user); navigate('/profile'); };
  return <div className="auth-wrap"><div className="card auth-card" style={{ maxWidth: 620 }}><span className="eyebrow">Настройка арены · шаг {step} из 2</span><div className="stepper"><span className="active" /><span className={step === 2 ? 'active' : ''} /></div>{step === 1 ? <><h1 className="display">О чём хотите говорить увереннее?</h1><p className="muted">Выберите от одной до трёх ситуаций. Это настроит вашу первую подборку.</p><div className="category-grid" style={{ gridTemplateColumns: 'repeat(2,1fr)', marginTop: 25 }}>{categories.map(({ name, icon: Icon }) => <button className={`option ${selected.includes(name) ? 'selected' : ''}`} key={name} onClick={() => toggle(name)} style={{ minHeight: 78 }} data-testid={`button-category-${name}`}><Icon size={17} /><span style={{ display: 'block', marginTop: 12 }}>{name}</span>{selected.includes(name) && <Check size={15} style={{ float: 'right', color: '#9de3e5' }} />}</button>)}</div><button className="btn btn-primary" disabled={!selected.length} onClick={() => setStep(2)} style={{ marginTop: 24, width: '100%' }} data-testid="button-onboarding-next">Продолжить <ArrowRight size={16} /></button></> : <><h1 className="display">Какой у вас опыт?</h1><p className="muted">Мы подберём первый уровень нагрузки. Его можно изменить перед каждой тренировкой.</p><div style={{ display: 'grid', gap: 10, marginTop: 25 }}>{['Новичок', 'Практик', 'Эксперт'].map(item => <button className={`option ${experience === item ? 'selected' : ''}`} key={item} onClick={() => setExperience(item)} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }} data-testid={`button-experience-${item}`}>{item}<span className="muted">{item === 'Новичок' ? 'Лёгкий старт' : item === 'Практик' ? 'Средний темп' : 'Сложные вводные'}</span>{experience === item && <Check size={15} />}</button>)}</div><div style={{ display: 'flex', gap: 10, marginTop: 24 }}><button className="btn btn-quiet" onClick={() => setStep(1)}><ArrowLeft size={16} /> Назад</button><button className="btn btn-primary" disabled={!experience} onClick={finish} style={{ flex: 1 }} data-testid="button-onboarding-finish">Войти в профиль <ArrowRight size={16} /></button></div></>}</div></div>;
}
